# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import operarios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ImageField(blank=True, upload_to=operarios.models.operario_directory_path)),
                ('genero', models.CharField(blank=True, max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, max_length=40, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('celular', models.CharField(blank=True, max_length=10)),
                ('estado', models.CharField(blank=True, max_length=1)),
                ('intentos', models.CharField(blank=True, max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Crear Operario',
            },
        ),
    ]
