# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabeza_Nucleo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c2', models.TextField(blank=True)),
                ('id_c2', models.TextField(blank=True)),
                ('c3', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=1)),
                ('c4', models.TextField(blank=True)),
                ('id_c4', models.TextField(blank=True)),
                ('c4_puntaje', models.CharField(blank=True, max_length=15)),
                ('c4_folio', models.CharField(blank=True, max_length=15)),
                ('c5', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=1)),
                ('c5_beneficio', models.TextField(blank=True)),
                ('id_c5_beneficio', models.TextField(blank=True)),
                ('c6', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=1)),
                ('c6_beneficio', models.CharField(blank=True, choices=[(b'D', b'Departamental'), (b'M', b'Municipal'), (b'O', b'ONG'), (b'X', b'Otro')], max_length=1)),
                ('c7', models.CharField(blank=True, choices=[(b'G', b'Gestacion'), (b'L', b'Lactando'), (b'N', b'Ninguna')], max_length=1)),
                ('c8', models.TextField(blank=True)),
                ('id_c8', models.TextField(blank=True)),
                ('c9', models.TextField(blank=True)),
                ('id_c9', models.TextField(blank=True)),
                ('c10', models.TextField(blank=True)),
                ('id_c10', models.TextField(blank=True)),
                ('c11', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Crear Cabeza de Nucleo',
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(blank=True)),
                ('numero_documento', models.CharField(blank=True, max_length=15)),
                ('edad', models.CharField(blank=True, max_length=2)),
                ('sabe_leer', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=1)),
                ('sabe_escribir', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=1)),
                ('n_dias_labora', models.CharField(blank=True, choices=[(b'1', b'1 Dia'), (b'2', b'2 Dias'), (b'3', b'3 Dias'), (b'4', b'4 Dias'), (b'5', b'5 Dias'), (b'6', b'6 Dias'), (b'7', b'7 Dias')], max_length=1)),
                ('n_horas_labora', models.CharField(blank=True, choices=[(b'1', b'1 Hora'), (b'2', b'2 Horas'), (b'3', b'3 Horas'), (b'4', b'4 Horas'), (b'5', b'5 Horas'), (b'6', b'6 Horas'), (b'7', b'7 Horas'), (b'8', b'8 Horas'), (b'8-12', b'8 a 12 Horas'), (b'12', b'Mas de 12 Horas')], max_length=1)),
                ('condiciones_especiales', models.CharField(blank=True, choices=[(b'VC', b'Victima Conflicto'), (b'CD', b'Con Discapacidad'), (b'VD', b'Victima Desastres'), (b'OC', b'Otra Condicion'), (b'NA', b'Ninguna de las Anteriores')], max_length=2)),
                ('aporta_sustento', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=1)),
                ('estado_sgsss', models.CharField(blank=True, choices=[(b'A', b'Afiliado'), (b'D', b'Desafiliado')], max_length=1)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
            ],
            options={
                'verbose_name_plural': 'Crear Familiar',
            },
        ),
    ]
