# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caracteristicas_vivienda', '0001_initial'),
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicasvivienda',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Ciudades'),
        ),
        migrations.AddField(
            model_name='caracteristicasvivienda',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Departamentos'),
        ),
        migrations.AddField(
            model_name='caracteristicasvivienda',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Paises'),
        ),
        migrations.AddField(
            model_name='caracteristicasvivienda',
            name='tipo_tenencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caracteristicas_vivienda.Tipo_Tenencia_Vivienda'),
        ),
        migrations.AddField(
            model_name='caracteristicasvivienda',
            name='tipo_vivienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='caracteristicas_vivienda.Tipo_Vivienda'),
        ),
    ]
