# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=2)),
                ('f2', models.CharField(blank=True, max_length=2)),
                ('semana_nacimiento', models.CharField(blank=True, max_length=4)),
                ('tipo_parto', models.CharField(blank=True, max_length=2)),
                ('servicio_parto', models.CharField(blank=True, max_length=2)),
                ('f4', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=2)),
                ('f5', models.TextField(blank=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
                ('f3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.EPS')),
            ],
        ),
    ]
