# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beneficiarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadControles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.CharField(blank=True, max_length=20)),
                ('cantidad', models.CharField(blank=True, max_length=20)),
                ('fecha', models.CharField(blank=True, max_length=10)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Controles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20)),
                ('fecha_control', models.CharField(max_length=10)),
                ('edad_anios', models.CharField(max_length=2)),
                ('edad_meses', models.CharField(max_length=2)),
                ('peso_kilos', models.CharField(max_length=2)),
                ('peso_gramos', models.CharField(max_length=4)),
                ('talla', models.CharField(max_length=3)),
                ('interpretacion', models.TextField(blank=True)),
                ('peso_idealK', models.CharField(blank=True, max_length=2)),
                ('peso_idealG', models.CharField(blank=True, max_length=4)),
                ('talla_ideal', models.CharField(blank=True, max_length=3)),
                ('estado', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Examenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toma', models.CharField(blank=True, max_length=10)),
                ('diagnostico', models.CharField(blank=True, choices=[(b'DA', b'Desnutrici\xc3\xb3n Aguda'), (b'DG', b'Desnutrici\xc3\xb3n Global'), (b'RA', b'Riesgo de Desnutrici\xc3\xb3n Aguda'), (b'RG', b'Riesgo Desnutrici\xc3\xb3n Global'), (b'OB', b'Obesidad'), (b'SO', b'Sobrepeso'), (b'RC', b'Retraso en el Crecimiento'), (b'RR', b'Riesgo de Retraso en el Crecimiento'), (b'EU', b'Eutr\xc3\xb3fico (normal)')], max_length=2)),
                ('examenen', models.CharField(blank=True, choices=[(b'CH', b'Cuadro Hem\xc3\xa1tico'), (b'TH', b'THS'), (b'T3', b'T3'), (b'T4', b'Hormonas Tiroideas'), (b'PL', b'Perfil Lip\xc3\xaddico'), (b'PS', b'Proteinas en Sangre'), (b'ES', b'Electrolitos en Sangre'), (b'HC', b'Hormona del Crecimiento'), (b'CP', b'Coprol\xc3\xb3gico'), (b'GC', b'Glicemia'), (b'BS', b'Basal')], max_length=2)),
                ('programa', models.CharField(blank=True, choices=[(b'CR', b'Centro de Recuperaci\xc3\xb3n Nutricional'), (b'RA', b'Recuperaci\xc3\xb3n Nutricional Ambulatoria'), (b'PL', b'Programas Liderados (Municipio/Distrito)'), (b'RN', b'Recuperaci\xc3\xb3n Nutricional Comunitaria'), (b'NI', b'Ninguno'), (b'OT', b'Otro')], max_length=2)),
                ('otro', models.CharField(blank=True, max_length=30)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_nacer', models.CharField(blank=True, max_length=4)),
                ('talla_nacer', models.CharField(blank=True, max_length=4)),
                ('e3', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=2)),
                ('e4', models.TextField(blank=True)),
                ('e4_f1', models.CharField(blank=True, max_length=10)),
                ('e4_f2', models.CharField(blank=True, max_length=10)),
                ('e4_f3', models.CharField(blank=True, max_length=10)),
                ('e5', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=2)),
                ('e6', models.CharField(blank=True, choices=[(b'MA', b'Leche materna complementada con alimentaci\xc3\xb3n familiar '), (b'VA', b'Leche de vaca y alimentaci\xc3\xb3n familiar'), (b'LF', b'Leche de formula'), (b'AF', b'Alimentaci\xc3\xb3n familiar'), (b'FA', b'Leche de formula y alimentaci\xc3\xb3n familiar'), (b'OF', b' Leche de otro mam\xc3\xadfero y alimentaci\xc3\xb3n familiar'), (b'OT', b'Otra')], max_length=2)),
                ('e6_otra', models.TextField(blank=True)),
                ('e7', models.CharField(blank=True, choices=[(b'MA', b'Leche materna complementada con alimentaci\xc3\xb3n familiar '), (b'VA', b'Leche de vaca y alimentaci\xc3\xb3n familiar'), (b'LF', b'Leche de formula'), (b'AF', b'Alimentaci\xc3\xb3n familiar'), (b'FA', b'Leche de formula y alimentaci\xc3\xb3n familiar'), (b'OF', b' Leche de otro mam\xc3\xadfero y alimentaci\xc3\xb3n familiar'), (b'OT', b'Otra')], max_length=2)),
                ('e7_otra', models.TextField(blank=True)),
                ('t1_d8', models.TextField(blank=True)),
                ('id_t1_d8', models.TextField(blank=True)),
                ('e1_d8', models.TextField(blank=True)),
                ('id_e1_d8', models.TextField(blank=True)),
                ('a1_d8', models.TextField(blank=True)),
                ('id_a1_d8', models.TextField(blank=True)),
                ('t2_d8', models.TextField(blank=True)),
                ('id_t2_d8', models.TextField(blank=True)),
                ('e2_d8', models.TextField(blank=True)),
                ('id_e2_d8', models.TextField(blank=True)),
                ('a2_d8', models.TextField(blank=True)),
                ('id_a2_d8', models.TextField(blank=True)),
                ('t3_d8', models.TextField(blank=True)),
                ('id_t3_d8', models.TextField(blank=True)),
                ('e3_d8', models.TextField(blank=True)),
                ('id_e3_d8', models.TextField(blank=True)),
                ('a3_d8', models.TextField(blank=True)),
                ('id_a3_d8', models.TextField(blank=True)),
                ('t4_d8', models.TextField(blank=True)),
                ('id_t4_d8', models.TextField(blank=True)),
                ('e4_d8', models.TextField(blank=True)),
                ('id_e4_d8', models.TextField(blank=True)),
                ('a4_d8', models.TextField(blank=True)),
                ('id_a4_d8', models.TextField(blank=True)),
                ('e9', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=2)),
                ('e10', models.CharField(blank=True, max_length=10)),
                ('e11', models.CharField(blank=True, choices=[(b'S', b'SI'), (b'N', b'NO')], max_length=2)),
                ('e11_cual', models.TextField(blank=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.Beneficiario')),
            ],
        ),
    ]
