# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 21:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Crear Ciudades o Municipios',
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Crear Departamento',
            },
        ),
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Crear EPS',
            },
        ),
        migrations.CreateModel(
            name='Estado_Laboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_laboral', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Crear Estados Laborales',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('detalle', models.CharField(max_length=40)),
                ('referencia', models.CharField(max_length=40)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now)),
                ('hora', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operarios.Operario')),
            ],
        ),
        migrations.CreateModel(
            name='Metas_Cabeza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metas', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Crear Metas Proyectadas a Cabezas de Hogar',
            },
        ),
        migrations.CreateModel(
            name='Nivel_Escolaridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_escolaridad', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Crear Nivel de Escolaridad',
            },
        ),
        migrations.CreateModel(
            name='No_EPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa_no_eps', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Crear Causas que llevan a no tener EPS',
            },
        ),
        migrations.CreateModel(
            name='Ocupaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Crear Ocupacion',
            },
        ),
        migrations.CreateModel(
            name='Organizaciones_Civiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacion', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Crear Organizaciones Civiles',
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Crear Pais',
            },
        ),
        migrations.CreateModel(
            name='Parentezco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentezco', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Crear Parentezco',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Crear Tipos de Documento',
            },
        ),
        migrations.AddField(
            model_name='departamentos',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Paises'),
        ),
        migrations.AddField(
            model_name='ciudades',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Departamentos'),
        ),
    ]
