# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad_Administradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Crear Entidad Administradora del Servicio',
            },
        ),
        migrations.CreateModel(
            name='Modalidades_servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Crear Modaliades del Servicio',
            },
        ),
        migrations.CreateModel(
            name='UDS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True)),
                ('direccion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Crear UDS',
            },
        ),
    ]
