# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-10 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidad_administradora_servicio', '0001_initial'),
        ('parametrizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uds',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Ciudades'),
        ),
        migrations.AddField(
            model_name='uds',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Departamentos'),
        ),
        migrations.AddField(
            model_name='uds',
            name='entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad_administradora_servicio.Entidad_Administradora'),
        ),
        migrations.AddField(
            model_name='uds',
            name='modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad_administradora_servicio.Modalidades_servicio'),
        ),
        migrations.AddField(
            model_name='uds',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Paises'),
        ),
        migrations.AddField(
            model_name='entidad_administradora',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrizacion.Tipo_Documento'),
        ),
    ]
